### PR TITLE
r.vol.dem: fix Boolean types

### PR DESCRIPTION
**Pull request by neteler**
Backport of v.hull related changes (https://github.com/OSGeo/grass/pull/1567) to fix compilation error:

```
gcc  -Werror-implicit-function-declaration -fno-common   -I/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/include -I/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/include    -DPACKAGE=\""grassmods"\"   -I/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/include -I/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/include -DRELDIR=\"/home/neteler/src/grass-addons/grass7/raster/r.vol.dem\" -o OBJ.x86_64-pc-linux-gnu/chull.o -c chull.c
In file included from /home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/include/grass/gis.h:26,
                 from chull.c:26:
chull.c:32:19: error: expected ‘;’, identifier or ‘(’ before ‘_Bool’
 { BFALSE, BTRUE } bool;
                   ^~~~
```

See current https://grass.osgeo.org/addons/grass7/logs/r.vol.dem.log

### CODE REVIEW

**Comment by nilason** [comment]
To keep pre 7.8.6 release compatibility this need slight variation. Probably something like `#ifndef  __bool_true_false_are_defined` `bool`, `true` and `false` need to be defined locally. Cannot test this in a couple of days, but will look at it soon as possible.

File: grass7/raster/r.vol.dem/chull.c [hunk 1]
```diff
@@ -27,10 +27,6 @@
 
 #include "globals.h"
 
-/*Define Boolean type */
-typedef enum
-{ BFALSE, BTRUE } bool;
-
```
Comment (nilason) [inline grass7/raster/r.vol.dem/chull.c:33]: With the following modification to existing PR, it should work with pre-7.8.6 GRASS too.

```diff
@@ -27,6 +27,12 @@
 
 #include "globals.h"
 
+#ifndef __bool_true_false_are_defined
+/* Define Boolean type for pre-7.8.6 compatibility */
+typedef enum
+{ false = FALSE, true = TRUE } bool;
+#endif
+
 /* Define vertex indices. */
 #define X   0
 #define Y   1
```

Small explanation: with 7.8.6 `stdbool.h` is included in `gis.h` (which is in turn included in `chull.c`). stdbool.h defines `__bool_true_false_are_defined = 1`: [stdbool.h specs](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stdbool.h.html).

For 7.8.5 and earlier versions, stdbool.h is **not** included, `__bool_true_false_are_defined` is not true and local definition of bool is made.

*I have tested the above code and logic in test code, not with the actual extension.*

**Review by nilason — CHANGES_REQUESTED** [review]

File: grass7/raster/r.vol.dem/chull.c (hunk 1 above)
Comment (neteler) [reply grass7/raster/r.vol.dem/chull.c]: Thanks a lot, @nilason - changes added in f82f1107

**Review by nilason — APPROVED** [review]
Looks good to me now, thanks!

**Comment by neteler** [comment]
> Looks good to me now, thanks!

Thanks for your support!
