### ISSUE TITLE
[Bug] `r.flowaccumulation` fails to compile with GRASS 8.4.1 on Ubuntu 24.04?

### ISSUE THREAD

**Issue by wangzcl** [OSGeo/grass-addons#1490]
**Name of the addon**
`r.flowaccumulation` by @HuidaeCho 

**Describe the bug**
The extension fails to compile during installation because the function `G_set_omp_num_threads` is not defined. Is there a header file (like `gis.h`) that is yet to be included, or it is a problem with my GRASS release?

```
GRASS > g.extension r.flowaccumulation
Fetching <r.flowaccumulation> from <https://github.com/OSGeo/grass-addons/>
(be patient)...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 62 (delta 1), reused 1 (delta 1), pack-reused 46 (from 1)
Receiving objects: 100% (62/62), 620.98 KiB | 11.29 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Already on 'grass8'
Your branch is up to date with 'origin/grass8'.
Compiling...
main.c: In function ‘main’:
main.c:149:19: warning: implicit declaration of function ‘G_set_omp_num_threads’; did you mean ‘omp_set_num_threads’? [-Wimplicit-function-declaration]
  149 |     num_threads = G_set_omp_num_threads(opt.nprocs);
      |                   ^~~~~~~~~~~~~~~~~~~~~
      |                   omp_set_num_threads
/usr/bin/ld: /tmp/grass8-zwang505-454058/ccNd1tWR.ltrans1.ltrans.o: in function `main':
/tmp/grass8-zwang505-454058/tmpcsz9xm_u/r.flowaccumulation/grass_addons/src/raster/r.flowaccumulation/main.c:149:(.text.startup+0x36a): undefined reference to `G_set_omp_num_threads'
collect2: error: ld returned 1 exit status
make: *** [/usr/lib/grass84/include/Make/Module.make:18: /tmp/grass8-zwang505-454058/tmpcsz9xm_u/r.flowaccumulation/grass_addons/src/raster/r.flowaccumulation/bin/r.flowaccumulation] Error 1
ERROR: Compilation failed, sorry. Please check above error messages.
```

**To Reproduce**
Simply start GRASS and run `g.extension r.flowaccumulation`.

**System description (please complete the following information):**

- Operating System: Linux Ubuntu 24.04
- GRASS GIS version 8.4.1 (from ppa:ubuntugis-unstable)
- details about further software components
```
GRASS > g.version -rge
version=8.4.1
date=2025
revision=exported
build_date=2025-07-21
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=8.4.1
libgis_date=2025-07-21T15:11:31+00:00
proj=9.4.1
gdal=3.11.3
geos=3.12.2
sqlite=3.45.1

GRASS > grass --config build
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr/lib --enable-largefile --enable-socket --enable-shared --with-blas --with-bzlib --with-cairo --with-cxx --with-freetype --with-freetype-includes=/usr/include/freetype2 --with-gdal --with-geos --with-lapack --with-motif --with-mysql --with-mysql-includes=/usr/include/mysql --with-netcdf --with-nls --with-odbc --with-openmp --with-pdal --with-postgres --with-postgres-includes=/usr/include/postgresql --with-proj-share=/usr/share/proj --with-python --with-readline --with-sqlite --with-x --with-zstd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/grass-khB6MT/grass-8.4.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/grass-khB6MT/grass-8.4.1=/usr/src/grass-8.4.1-1~noble4 -Wno-error=format-security -Wall -DNDEBUG LDFLAGS=-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro -Wl,-z,now CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=3 CXXFLAGS=-g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/build/grass-khB6MT/grass-8.4.1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/build/grass-khB6MT/grass-8.4.1=/usr/src/grass-8.4.1-1~noble4
```
`grass-dev` and `build-essential` are up to date.

Thanks!

**Comment by nilason** [comment]
`G_set_omp_num_threads()` is only on 8.5, we need to conditionalise this for <8.5.

**Comment by wangzcl** [comment]
I think this also applies to `r.hydrobasin` and `r.lfp` as well.

**Comment by HuidaeCho** [comment]
Fixed in #1491, #1492, #1493.

**Comment by wangzcl** [comment]
I think problems are solved. I'll close this issue. Cheers and thanks @HuidaeCho !
